Fix deepmind log not reset properly 2.1.x
EOSIO/fc pull request #216
Opened 2021-10-26 05:21 UTC by Duncan-Ultra

When start and stop nodeos with deepmind enabled, there will be a chance that `is_stopped` being held, and if `is_stopped = true`, this will cause and next run to return true and only print out `DMLOG FPRINTF_FAILURE_TERMINATED` for all deepmind log.

2021-10-26 15:16 UTC, heifner requested changes

2021-10-26 15:16 UTC, heifner commented on src/log/dmlog_appender.cpp
> +      // which might cause logger to print wrong DMLOG if is_stopped is true in previous run
This comment is not what is happening here. The issue is that `is_stopped` is uninitialized and therefore can be any value on startup. Line 19 should be `bool is_stopped = false;`.
Also the `log_mutex` and locking of the mutex is not needed. The logging framework already has a mutex around logging. See `logger::log( log_message m )` implementation which grabs a lock before calling the appenders.

2021-10-27 05:47 UTC, Duncan-Ultra commented on src/log/dmlog_appender.cpp
> +      // which might cause logger to print wrong DMLOG if is_stopped is true in previous run
@heifner thanks
I update according to your recommendation: remove mutex lock and initialize is_stopped.
All tested and working fine with dfuse.
https://github.com/EOSIO/fc/pull/216/commits/4e3c35fdcfb5a38169841251f5147257a911cad6

I already updated PR for 2.2.x as well, lemme know if i need to make another PR for any required branch.

2021-10-27 12:21 UTC, heifner approved these changes

2021-10-27 12:22 UTC, heifner commented on src/log/dmlog_appender.cpp
> +      // which might cause logger to print wrong DMLOG if is_stopped is true in previous run
Please create a PR to the `eosio` branch which is the "develop" branch of `fc`.

2021-10-27 12:54 UTC, Duncan-Ultra commented on src/log/dmlog_appender.cpp
> +      // which might cause logger to print wrong DMLOG if is_stopped is true in previous run
@heifner
PR created - https://github.com/EOSIO/fc/pull/218

2021-10-27 18:03 UTC, heifner commented on src/log/dmlog_appender.cpp
> +      // which might cause logger to print wrong DMLOG if is_stopped is true in previous run
Thanks. You are free to merge them in or let me know if you don't have the green button.

2021-10-28 03:50 UTC, Duncan-Ultra commented on src/log/dmlog_appender.cpp
> +      // which might cause logger to print wrong DMLOG if is_stopped is true in previous run
@heifner thanks, well I actually don't have green button for merge.

2021-10-28 12:09 UTC, merged